add annotation for phone validation and test
SashaRoyenko/EJournal-Service pull request #19
Opened 2020-04-07 12:59 UTC by NazarShchur

2020-04-07 17:22 UTC, SashaRoyenko requested changes

2020-04-07 17:22 UTC, SashaRoyenko commented on src/main/java/com/robosh/ejournal/data/entity/User.java
>      @Column(name = "phone")
Rename please to Phone

2020-04-07 17:22 UTC, SashaRoyenko commented on src/main/java/com/robosh/ejournal/util/validation/regex/Regex.java
> +package com.robosh.ejournal.util.validation.regex;
Move to constant package

2020-04-08 10:28 UTC, SashaRoyenko approved these changes

2020-04-08 10:41 UTC, Ostape approved these changes

2020-04-08 10:41 UTC, merged