Rd 69 get save update teacher
SashaRoyenko/EJournal-Service pull request #30
Opened 2020-05-01 11:18 UTC by NazarShchur

endpoints for teacher + tests

2020-05-01 12:27 UTC, SashaRoyenko requested changes

2020-05-01 12:27 UTC, SashaRoyenko commented on src/main/java/com/robosh/ejournal/service/TeacherService.java
> +
Retrieve this method to Util class and make it reusable. Reflection will help you

2020-05-01 15:22 UTC, Ostape approved these changes

2020-06-24 15:58 UTC, SashaRoyenko commented
Hi @NazarShchur, what is your progress?

2020-06-25 09:45 UTC, SashaRoyenko commented on src/main/java/com/robosh/ejournal/service/TeacherService.java
> +
I decided to do this at separate task

2020-06-25 09:46 UTC, SashaRoyenko approved these changes

2020-06-25 09:46 UTC, merged